"""initial case tables

Revision ID: f51e3a54fd56
Revises: 
Create Date: 2026-08-18 15:48:08.640551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51e3a54fd56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('initial_visit', 'follow_up_visit', name='casetype'), nullable=False),
    sa.Column('system_tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('language_availability', sa.JSON(), nullable=False),
    sa.Column('sections_language', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('student_instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'published', name='casestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('reviewer_name', sa.String(length=80), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('examiner_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('case_summary', sa.Text(), nullable=False),
    sa.Column('working_diagnosis', sa.Text(), nullable=False),
    sa.Column('differentials', sa.JSON(), nullable=False),
    sa.Column('structured_questions', sa.JSON(), nullable=False),
    sa.Column('suggested_answers', sa.JSON(), nullable=False),
    sa.Column('physical_exam_release', sa.JSON(), nullable=False),
    sa.Column('investigation_release', sa.JSON(), nullable=False),
    sa.Column('scoring_rubric', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('patient_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('ethnicity', sa.String(length=80), nullable=True),
    sa.Column('patient_language', sa.String(length=40), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('history_of_present_illness', sa.Text(), nullable=False),
    sa.Column('review_of_systems', sa.JSON(), nullable=False),
    sa.Column('past_medical_history', sa.JSON(), nullable=False),
    sa.Column('past_surgical_history', sa.Text(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('personal_social_history', sa.JSON(), nullable=False),
    sa.Column('sexual_history', sa.Text(), nullable=True),
    sa.Column('obgyn_history', sa.Text(), nullable=True),
    sa.Column('opening_statement', sa.Text(), nullable=False),
    sa.Column('affect_style', sa.Text(), nullable=True),
    sa.Column('ice', sa.JSON(), nullable=False),
    sa.Column('disclosure_rules', sa.JSON(), nullable=False),
    sa.Column('qa_triggers', sa.JSON(), nullable=False),
    sa.Column('default_negative_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_information')
    op.drop_table('examiner_packs')
    op.drop_table('case_review_records')
    op.drop_table('cases')
    # ### end Alembic commands ###
